#define LOCALHOST "0.0.0.0"
// #define QUERY_ENGINE_PORT "40100" 
#define QUERY_ENGINE_PORT "22222"

// #define STORAGE_ENGINE_IP getenv("INSTANCE_CLUSTER_MASTER_IP")
#define STORAGE_ENGINE_IP "0.0.0.0"

// #define SE_INTERFACE_PORT getenv("SE_INTERFACE_NODE_PORT")
#define SE_INTERFACE_PORT "40200"
